# Use environment variables from .env
services:
  nats:
    image: nats:latest
    ports:
      - "${DOCKER_HOST}:${NATS_BASIC_PORT}:4222"
      - "${DOCKER_HOST}:${NATS_BASIC_CLUSTER_PORT}:6222"
      - "${DOCKER_HOST}:${NATS_BASIC_HTTP_PORT}:8222"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: "--user ${NATS_USER} --pass ${NATS_PASSWORD} --cluster_name ${NATS_BASIC_CLUSTER_NAME} --cluster nats://0.0.0.0:6222 --http_port 8222"

  nats_tls:
    image: nats:latest
    ports:
      - "${DOCKER_HOST}:${NATS_TLS_PORT}:4222"
      - "${DOCKER_HOST}:${NATS_TLS_CLUSTER_PORT}:6222"
    environment:
      - NATS_TLS_PORT=${NATS_TLS_PORT}
      - NATS_TLS_CLUSTER_PORT=${NATS_TLS_CLUSTER_PORT}
    command: >
      --user ${NATS_USER}
      --pass ${NATS_PASSWORD}
      --tls
      --tlscert /etc/nats-certs/server.crt
      --tlskey /etc/nats-certs/server.key
      --cluster_name ${NATS_BASIC_CLUSTER_NAME}
      --cluster nats://0.0.0.0:6222
      --http_port 8222
    volumes:
      - ./src/tls/nats:/etc/nats-certs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    ports:
      - "${DOCKER_HOST}:${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis_tls:
    image: redis:latest
    ports:
      - "${DOCKER_HOST}:${REDIS_TLS_PORT}:6379"
    command:
      - redis-server
      - --tls-port
      - "6379"
      - --port
      - "0"
      - --tls-cert-file
      - /etc/redis/certs/server.crt
      - --tls-key-file
      - /etc/redis/certs/server.key
      - --tls-ca-cert-file
      - /etc/redis/certs/ca.crt
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - ./src/tls/redis:/etc/redis/certs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "${DOCKER_HOST}:${RABBITMQ_PORT}:5672"
      - "${DOCKER_HOST}:${RABBITMQ_MANAGER_PORT}:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # rabbitmq_tls:
  #   image: rabbitmq:management
  #   ports:
  #     - "${RABBITMQ_TLS_PORT}:5672"
  #     - "15673:15672"
  #   environment:
  #     - RABBITMQ_TLS_PORT=${RABBITMQ_TLS_PORT}
  #   command: ["rabbitmq-server", "--ssl"]
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
